FROM node:carbon

ENV ROOT_DIR = '/app'

# Create working directory
WORKDIR $ROOT_DIR

# Bundle app source
COPY . .

# Install app dependencies
#RUN npm install --only=production --quiet

CMD ["npm", "start"]