version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    container_name: server_on_dnw
    environment:
      API_VERSION: "${API_VERSION}"
      API_KEY: "${API_KEY}"
      AUTH_USR: "${AUTH_USR}"
      AUTH_PW: "${AUTH_PW}"
      DB_HOST: mysql_on_dnw
      DB_NAME: "${DB_NAME}"
      DB_TBL_NAME: "${DB_TBL_NAME}"
      DB_PORT: "${DB_PORT}"
      DB_USR: "${DB_USR}"
      DB_USR_PW: "${DB_USR_PW}"
      PORT: "${PORT}"
      RUN_ENV: "${RUN_ENV}"
    env_file:
      - .env
    ports:
      - '127.0.0.1:${PORT}:${PORT}'

  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    container_name: mysql_on_dnw
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpw
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USR}"
      MYSQL_PASSWORD: "${DB_USR_PW}"
    env_file:
      - .env
    ports:
      - '127.0.0.1:${DB_PORT}:${DB_PORT}'