version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - '8081:8081'
    container_name: server_on_dnw
    environment:
      API_VERSION: 1
      API_KEY: m3FUxbLExcUqxpYw
      AUTH_USR: admin
      AUTH_PW: admin
      DB_HOST: mysql_on_dnw
      DB_NAME: g2t3cnwd
      DB_TBL_NAME: e4f9rN9e
      DB_PORT: 3306
      DB_USR: u7yme2bt
      DB_USR_PW: RzPHyvgJpXzLNY3yN7Pdu7HXVYUTJNeN
      PORT: 8081
      RUN_ENV: local

  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - '3306:3306'
    container_name: mysql_on_dnw
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpw
      MYSQL_DATABASE: g2t3cnwd
      MYSQL_USER: u7yme2bt
      MYSQL_PASSWORD: RzPHyvgJpXzLNY3yN7Pdu7HXVYUTJNeN