version: "3"
services:
  node:
    command: ["npm", "start"]
    container_name: node_on_dnw-PdnFd9
    environment:
      API_VERSION: "${API_VERSION}"
      API_KEY: "${API_KEY}"
      AUTH_USR: "${AUTH_USR}"
      AUTH_PW: "${AUTH_PW}"
      DB_HOST: mysql_on_dnw
      DB_NAME: "${DB_NAME}"
      DB_TBL_NAME: "${DB_TBL_NAME}"
      DB_PORT: "${DB_PORT}"
      DB_USR: "${DB_USR}"
      DB_USR_PW: "${DB_USR_PW}"
      PORT: "${PORT}"
      RUN_ENV: "${RUN_ENV}"
    env_file:
      - .env
    image: node:carbon
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    volumes:
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./build:/app/build
    working_dir: /app
    links:
      - mysql
      - mongodb

  mysql:
    container_name: mysql_on_dnw-7kYLNJ
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpw
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USR}"
      MYSQL_PASSWORD: "${DB_USR_PW}"
    env_file:
      - .env
    image: mysql:latest
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:3306:3306"

  mongodb:
    image: mongo:latest
    container_name: mongo_on_dnw-9PtqLv
    volumes:
      - ./data/mngdb:/data/db
      - .dbshell:/root/.dbshell
    environment:
      - MONGODB_USER="${MONGO_DB_USR}"
      - MONGODB_PASS="${MONGO_DB_PASS}"
    env_file:
      - .env